---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay
  namespace: default
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - env:
        - name: COW_COLOR
          value: white
        name: demo
        image: brooksphilip/rancher-demo-navlink
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cowsay
  namespace: default
spec:
  selector:
    app: demo
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cowsay-nodeport
  namespace: default
spec:
  selector:
    app: demo
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cowsay-loadbalancer
#   namespace: default
# spec:
#   selector:
#     app: demo
#   type: LoadBalancer
#   ports:
#   - name: http
#     port: 8080
#     protocol: TCP
#     targetPort: 8080
---
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: demo-navlink
spec:
  description: Demo App for Rancher
  group: Rancher Demo
  iconSrc: >-
    data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE5LjIuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCA1MDAuMiAyNTQiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDUwMC4yIDI1NDsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJLnN0MHtmaWxsOiMyNDUzRkY7fQoJLnN0MXtmaWxsOiMwMDAwMDA7fQoJLnN0MntmaWxsOiNDQ0NDQ0M7fQoJLnN0M3tmaWxsOiNCM0IzQjM7fQoJLnN0NHtmaWxsOiNGRkZGRkY7fQo8L3N0eWxlPgo8cGF0aCBjbGFzcz0ic3QxIiBkPSJNMS42LDE2OS41aDM0LjJjMTYuMiwwLDI3LjIsNy45LDI3LjIsMjMuMWMwLDEyLjQtOC41LDE5LjktMTYuNywyMi41YzIuNSwyLjEsNC4zLDQuOSw1LjgsNy45CgljMy40LDcsNS44LDE0LjgsMTMsMTQuOGMxLjgsMCwzLjMtMC42LDMuMy0wLjZsLTEuNiwxNC42YzAsMC00LjQsMS4xLTguMiwxLjFjLTkuOCwwLTE1LjUtMy44LTIxLjMtMTdjLTIuNS01LjktNS45LTE2LjItMTAuNS0xNi4yCgloLTQuN3YzMi44SDEuNlYxNjkuNXogTTIyLjEsMTg0LjR2MjAuNGg3LjRjNS45LDAsMTIuOC0xLjgsMTIuOC0xMC43YzAtNy4zLTQuNy05LjctMTAuMy05LjdIMjIuMXogTTkwLjgsMTY5LjVoMjAuOGwyOCw4M2gtMjAuOAoJbC01LjItMTUuN0g4NS45bC01LDE1LjdoLTE4TDkwLjgsMTY5LjV6IE05MC44LDIyMS41aDE3LjhsLTUuNy0xNy41Yy0yLTUuOS0yLjgtMTQuMy0yLjgtMTQuM2gtMC41YzAsMC0xLjIsOC41LTMuMSwxNC4xCglMOTAuOCwyMjEuNXogTTE0MC41LDI1Mi41aDE2Ljl2LTM5LjljMC00LjUtMC42LTEwLjEtMS0xNC44aDAuNWMxLjcsNC40LDMuOSw5LjgsNiwxMy41bDIyLjYsNDEuMUgyMDd2LTgzaC0xNi45djM5LjkKCWMwLDQuOCwwLjYsMTEuNCwwLjksMTYuMWgtMC41Yy0yLTQuOS00LjQtMTEuMi02LjMtMTQuOGwtMjEuOC00MS4yaC0yMlYyNTIuNXogTTIxMS40LDIxMC40YzAsMzAuMywxNC41LDQzLjUsMzcsNDMuNQoJYzIyLjEsMCwzNC4zLTEyLjQsMzMtMjkuM2wtMTgtMS44YzEuNSwxMC44LTUuNCwxNi4xLTEzLjksMTYuMWMtOSwwLTE2LjktNS44LTE2LjktMjguNGMwLTIxLjQsNy4zLTI4LDE2LjItMjgKCWM5LjMsMCwxNC41LDUuMywxMi40LDE4LjVsMTkuMi0xLjdjMi43LTE4LTctMzEuMi0zMS4yLTMxLjJDMjI2LjMsMTY4LDIxMS40LDE4MC40LDIxMS40LDIxMC40IE0yODUuNiwyNTIuNWgyMC41di0zNS4yaDI1LjJ2MzUuMgoJaDIwLjV2LTgzaC0yMC41djMxLjRoLTI1LjJ2LTMxLjRoLTIwLjVWMjUyLjV6IE0zNjAuMSwyNTIuNWg1Ni4ydi0xNS4zaC0zNS43di0xOS40aDI4Ljl2LTE1LjNoLTI4Ljl2LTE3LjhoMzQuNHYtMTUuM2gtNTVWMjUyLjV6CgkgTTQyMC4zLDE2OS41aDM0LjJjMTYuMiwwLDI3LjIsNy45LDI3LjIsMjMuMWMwLDEyLjQtOC41LDE5LjktMTYuNywyMi41YzIuNSwyLjEsNC4zLDQuOSw1LjgsNy45YzMuNCw3LDUuOCwxNC44LDEzLDE0LjgKCWMxLjgsMCwzLjMtMC42LDMuMy0wLjZsLTEuNiwxNC42YzAsMC00LjQsMS4xLTguMiwxLjFjLTkuOCwwLTE1LjUtMy44LTIxLjMtMTdjLTIuNS01LjktNS45LTE2LjItMTAuNS0xNi4yaC00Ljd2MzIuOGgtMjAuNVYxNjkuNXoKCSBNNDQwLjgsMTg0LjR2MjAuNGg3LjRjNS45LDAsMTIuOC0xLjgsMTIuOC0xMC43YzAtNy4zLTQuNy05LjctMTAuMy05LjdINDQwLjh6Ii8+CjxnPgoJPHBhdGggY2xhc3M9InN0MCIgZD0iTTM5My4yLDMwLjdMMzkwLDExLjNjLTEtNi4yLTMuNS0xMS4zLTUuNC0xMS4zYy0xLjksMC0zLjUsNS4yLTMuNSwxMS41djUuMWMwLDYuMy01LjIsMTEuNS0xMS41LDExLjVoLTUuMQoJCWMtMC40LDAtMC43LDAtMS4xLDBWNDJjMC40LDAsMC43LDAsMS4xLDBoMTkuMUMzODkuOSw0MiwzOTQuMiwzNi45LDM5My4yLDMwLjciLz4KCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0zNDcuNSwxNC4zaC0zMC45Yy0wLjMsMC0wLjUsMC0wLjgsMEgyODRjLTAuNCwwLTAuNywwLTEuMSwwLjF2LTNjMC02LjMtMS42LTExLjUtMy41LTExLjVzLTQuNCw1LjEtNS40LDExLjMKCQlsLTMuMiwxOS40Yy0xLDYuMiwzLjMsMTEuMyw5LjYsMTEuM2gxOS4xYzIsMCwzLjgtMC4zLDUuNC0wLjhjLTAuNiwzLjMtMy41LDUuNy02LjksNS43aC0yNi44Yy00LjMsMC03LjYtMy45LTYuOS04LjJsMi43LTE2LjMKCQljMC43LTQuMy0yLjYtOC4yLTYuOS04LjJIMTI3Yy0yLjgsMC01LjMsMS43LTYuNCw0LjFMOTUuNiw1Ni42Yy0wLjQsMC42LTAuNCwxLjUsMC4xLDIuMWw0LjksNS43YzAuNiwwLjcsMS43LDAuOCwyLjQsMC4ybDE3LTEzLjQKCQl2ODEuNmMwLDMuOSwzLjEsNyw3LDdoMzcuOGMzLjksMCw3LTMuMSw3LTd2LTI4LjRjMC0zLjksMy4xLTcsNy03aDk0LjRjMy45LDAsNywzLjEsNyw3djI4LjRjMCwzLjksMy4xLDcsNyw3SDMyNWMzLjksMCw3LTMuMSw3LTcKCQl2LTMwLjVoLTIwLjFjLTYuMywwLTExLjUtNS4yLTExLjUtMTEuNVY3MS4yYzAtMy43LDEuOC03LjEsNC42LTkuMnYyMy40YzAsNi4zLDUuMiwxMS41LDExLjUsMTEuNWgzMC45YzYuMywwLDExLjUtNS4yLDExLjUtMTEuNQoJCVYyNS44QzM1OC45LDE5LjUsMzUzLjgsMTQuMywzNDcuNSwxNC4zIi8+CjwvZz4KPHBhdGggY2xhc3M9InN0MSIgZD0iTTQ4Ny40LDE3My42YzAtMy45LDIuOS01LjYsNS42LTUuNnM1LjYsMS43LDUuNiw1LjZjMCwzLjgtMi45LDUuNS01LjYsNS41UzQ4Ny40LDE3Ny40LDQ4Ny40LDE3My42egoJIE00OTcuMywxNzMuNmMwLTMuMS0yLTQuNC00LjItNC40Yy0yLjIsMC00LjMsMS4zLTQuMyw0LjRjMCwzLDIuMSw0LjQsNC4zLDQuNEM0OTUuMywxNzgsNDk3LjMsMTc2LjYsNDk3LjMsMTczLjZ6IE00OTEuMiwxNzAuOGgyCgljMSwwLDIsMC4zLDIsMS43YzAsMC44LTAuNiwxLjMtMS4zLDEuNWwxLjMsMi4zSDQ5NGwtMS4yLTIuMmgtMC41djIuMmgtMS4xVjE3MC44eiBNNDkzLjIsMTczLjNjMC41LDAsMC45LTAuMywwLjktMC44CgljMC0wLjYtMC41LTAuNy0wLjktMC43aC0xdjEuNUg0OTMuMnoiLz4KPC9zdmc+Cg==
  label: Demo App
  sideLabel: Demo
  target: _blank
  toService:
    name: cowsay
    namespace: default
    path: /
    port: '8080'
    scheme: http
