# Default values for rancher-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: harbor.atoy.dev/public/rancher-demo-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "army"

config:
  backgroundColor: yellow
  loadbalancerEnabled: false
