---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay
  namespace: default
  labels:
    app: demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - env:
        - name: COW_COLOR
          value: {{ .Values.config.backgroundColor }}
        name: demo
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault