---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay
  namespace: default
  labels:
    app: demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env:
        - name: COW_COLOR
          value: {{ .Values.config.backgroundColor }}
        name: demo
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: 
            - "ALL"