{{- if .Values.config.loadbalancerEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: cowsay-loadbalancer
  namespace: default
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
{{- end }}
