apiVersion: v1
kind: Service
metadata:
  name: cowsay-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
