defaultNamespace: default

helm:
  chart: "./chart"
  valuesFiles:
  - values.yaml

targetCustomizations:
- name: red-background
  clusterSelector:
    matchLabels:
      background: red
  helm:
    values:
      config:
        backgroundColor: red